### PR TITLE
game_machine_1 added

### PR DESCRIPTION
**Pull request by aadityaforwork**

### CODE REVIEW

**Comment by aadityaforwork** [comment]
@r4pt0s added a game although it is basic for now I feel we can build upon it!

**Review by r4pt0s — CHANGES_REQUESTED** [review]
Could you resolve the merge conflict?
Also, your game will be opened in another browser window right?
Maybe you could rewrite it so that if works within the canvas instead of opening a new window.
You can also work with text input within the kaplay context
https://play.kaplayjs.com/?example=textInput

**Comment by aadityaforwork** [comment]
> Could you resolve the merge conflict? Also, your game will be opened in another browser window right? Maybe you could rewrite it so that if works within the canvas instead of opening a new window. You can also work with text input within the kaplay context https://play.kaplayjs.com/?example=textInput

Sure I will work upon it!

**Comment by r4pt0s** [comment]
@aadityaforwork I made a draft of it as long as you are working on it.

**Comment by aadityaforwork** [comment]
Hey @r4pt0s I have updated the game you can check it out there might be some less styling but I am sure that can be worked upon in the upcoming issues?

**Review by r4pt0s — APPROVED** [review]
🔥🔥🔥

**Pull request merged**
