### PR TITLE
Gba frame

### PR DESCRIPTION
**Pull request by Karine91**
Added frame for map, control position of camera

### CODE REVIEW

**Review by r4pt0s — CHANGES_REQUESTED** [review]
@Karine91 I totally like your approach. :fire: 
Can you check your styles in case of landscape mode on mobile?
Currently it looks like so on the mobile simulation view in chrome
bug_ui_landscape_mode

On a real device, there is no game canvasc visible at all in landscape mode.

Also, what do you think about the idea to hide the gamecontroller control buttons which you added completely on mobile devices? I mean, you  can totally work with viewport sizes as well. I would say, hide them below 750 px width? :thinking:

**Comment by Karine91** [comment]
@r4pt0s updated

**Comment by Karine91** [comment]
@r4pt0s ping)

**Review by r4pt0s — APPROVED** [review]

**Comment by r4pt0s** [comment]
🔥🔥🔥

**Pull request merged**
