### PR TITLE
fix:canvas focus after dialogs fixed

### LINKED ISSUE #49: Keyboard controls break after an interaction
After closing an interaction you are unable to move the player with the keyboard. Once you have moved the player again with the mouse you can continue to use the keyboard. 

### How to replicate: 
1. Interact with the mailbox or Bruno
2. Close the dialogue
3. Try to use the arrow keys to move around

### PR DESCRIPTION
**Pull request by bruno-keiko**
Fix #49

### CODE REVIEW

**Comment by KevinBatdorf** [comment]
If https://github.com/zero-to-mastery/ZTM-Quest/pull/54 gets merged then we could just do `k.canvas.focus()` even.

**Review by r4pt0s — CHANGES_REQUESTED** [review]
Could you please resolve the merge conflicts 🙏

**Comment by bruno-keiko** [comment]
> Could you please resolve the merge conflicts 🙏

I've resolved it. If there's anything I need to change, please let me know. Thanks!

**Comment by KevinBatdorf** [comment]
Did you see my comment above? You can just use `k.canvas.focus()` and don't need to query the dom.

**Comment by bruno-keiko** [comment]
> Did you see my comment above? You can just use `k.canvas.focus()` and don't need to query the dom.

Yeah, I updated it. thank you for being so helpful

**Review by r4pt0s — APPROVED** [review]

**Pull request merged**
