### PR TITLE
Refactor dialog processing

### PR DESCRIPTION
**Pull request by KevinBatdorf**
I couldn't reproduce the bug in https://github.com/zero-to-mastery/ZTM-Quest/issues/76 but I refactored the code and removed some of the unnecessary logic. I'm hoping this addresses it.

I merged in the two character/no character functions and named it `displayDialogue`. This makes it easier to manage the next/close buttons and the name can easily be checked before prepending it to the string. It also narrows the surface for bugs.

Some new rules I introduced:
1. Refer to dialog (the box) and dialogue/text (the conversation)
2. All text passed into dialog should be an array

Can you test it out? I can make changes tomorrow if needed (or in a follow up PR if its good enough to merge)

closes https://github.com/zero-to-mastery/ZTM-Quest/issues/76

### CODE REVIEW

**Comment by KevinBatdorf** [comment]
I think this is ready to check now. Maybe the next refactor could merge the remaining two dialog functions, so you can pass the button label and callback for when it's clicked. I think it would make the code much more readable and less complex logic. I can do that over the weekend.

**Review by gdsouza1992 — APPROVED** [review]

**Comment by r4pt0s** [comment]
@KevinBatdorf awesome. Good job.
Can you please resolve the remaining merge conflict 🙏🏻

**Comment by KevinBatdorf** [comment]
> Can you please resolve the remaining merge conflict 🙏🏻

Done.

I think combining the options container would be a next step as well in a followup PR, and having one place for _all_ dialogs.

**Comment by r4pt0s** [comment]
@KevinBatdorf that is a good idea.

**Pull request merged**
