### PR TITLE
added current map into local storage

### PR DESCRIPTION
**Pull request by BrianCheung1**
# Changes
Changed original k.go function to save current scene into local storage
This way when user refreshes their page they remain on the same map they were on before

### CODE REVIEW

**Review by r4pt0s — CHANGES_REQUESTED** [review]
Hi @BrianCheung1,

Can you change to logic here?
Overriding the entire k.go function might lead to unpredictable behavior while updating kaplayjs itself.

There is a event which you can use to set the current scene in localstorage.
Have a look at [onSceneLeave](https://kaplayjs.com/doc/ctx/onSceneLeave/)

By using this event, we can set the current scene.

It would also be great if you can store the last known position from the character as well.

Can you check if this would be a valid option?

**Comment by BrianCheung1** [comment]
I've changed it so that we now use OnSceneLeave instead of changing the original go function

I'm currently the position of the player only when they enter a new scene so it doesn't update properly every frame. I was unsure how you wanted me to handle that. Should I set it so that on every frame the player pos is saved or everytime the player moves using WASD/Mouse movements.

I'm also unsure if the placement of where I created the k.OnSceneLeave was correct. Please let me know if it should be in its own file in core/kaplay/scenes or something like that

**Comment by BrianCheung1** [comment]
I was getting errors where the gameState was not resetting properly, I've added currentState = undefined when clearing save game

I've added player position to be saved every frame, this maybe should be changed to everytime the user clicks a movement instead of every frame

I've changed how to retrieve and set local storage using the already defined getGameState and setGameState

**Review by r4pt0s — APPROVED** [review]
🔥🔥🔥

**Pull request merged**
