### PR TITLE
Return focus to canvas after interactions with dialogs

### PR DESCRIPTION
**Pull request by Karine91**
Focus canvas after interactions to be able to continue moving with keyboard navigation
Fixed interaction with the drinks machine

### CODE REVIEW

**Comment by Karine91** [comment]
@r4pt0s was preparing new PR, but it's in the same branch - so everything here now...

**Comment by Karine91** [comment]
Fixed functionality of interaction with drink machine and some style updates for dialogs button

**Comment by Karine91** [comment]
@r4pt0s I was thinking about adding support for navigation between buttons in dialogs with a keyboard

**Review by r4pt0s — APPROVED** [review]
🔥🔥🔥

**Pull request merged**
