### PR TITLE
Mister fu interaction

### PR DESCRIPTION
**Pull request by MIhnatco**

### CODE REVIEW

**Comment by r4pt0s** [comment]
@MIhnatco do you plan to add additional charges for this PR?

**Comment by MIhnatco** [comment]
Hi...I would like....I am trying to understand the whole game...there is no interaction with misterFu when I collide with it on my computer.......but I assume you would like to close the PR...go ahead...I am going to study "kaplay" and see if what comes out.....
I hope I didn't do too much damage

Odoslané z Proton Mail pre Android

-------- Pôvodná správa --------
15. 10. 2024 18:39, Wolfgang Kreminger  napísal/a:

**Comment by r4pt0s** [comment]
@MIhnatco it is not that I want to close thd PR. I wanted to know if you want to add something to it 😊.
The interaction does not happen on collide anymore. You have to go to the character, then you will see a question mark in a question bubble. Then you can click on misterfu and the dialog starts.

**Comment by r4pt0s** [comment]
Closed due to inactivity

**Comment by MIhnatco** [comment]
Hi Wolfgang, I apologize for not finding the time to contribute yet. I wanted to check if this project will conclude at the end of the month, or if there might be an opportunity to return and contribute in the near future.

Odoslané z Proton Mail pre Android

-------- Pôvodná správa --------
27. 10. 2024 15:35, Wolfgang Kreminger  napísal/a:

**Pull request closed without merging**
