### PR TITLE
Arcade game

### PR DESCRIPTION
**Pull request by BrianCheung1**
added a simple dino arcade game
mostly used kaplay getting started guide to create level.
changed dino image to one I found.

### CODE REVIEW

**Comment by BrianCheung1** [comment]
There is currently a bug where if I enter the house 
it will create enormous lag.

however, to reproduce it is kinda hard. I have to walk into the house holding two directions at once I believe?
but at a certain angle/speed it will lag out the site.

I'm currently unsure why this happens though.

**Comment by r4pt0s** [comment]
@BrianCheung1 that is a totally good starting point. Do you want me to merge it and you improve upon it in the same issue?

**Comment by BrianCheung1** [comment]
Yes that would be perfect

**Comment by r4pt0s** [comment]
> There is currently a bug where if I enter the house it will create enormous lag.
> 
> however, to reproduce it is kinda hard. I have to walk into the house holding two directions at once I believe? but at a certain angle/speed it will lag out the site.
> 
> I'm currently unsure why this happens though.
> 
> Edit: Did a little bit more playing around with it, it seems that multiple player models are being created and that's whats probably causing the lag.

About the bug, I can reproduce it and also encountered it. We can work on it in a new issue.

**Pull request merged**
