### PR TITLE
added sounds to public

### PR DESCRIPTION
**Pull request by nishchalgv1**
Created music/sounds to public directory

issue: #23

### CODE REVIEW

**Review by r4pt0s — COMMENTED** [review]
@nishchalgv1 it appears like you just moved the files into another directory.
Is this the case or is here a commit missing in your PR?

**Comment by nishchalgv1** [comment]
> @nishchalgv1 it appears like you just moved the files into another directory. Is this the case or is here a commit missing in your PR?
Yes moved the files into another directory as that's what I understood from the issue. No commit missing. If that's not being asked in the issue, could you please elaborate more about it?

**Comment by r4pt0s** [comment]
@nishchalgv1 sure.
This issue basically means creating new music tracks or sounds like car sounds or ambient sounds which we can then add to game.

**Review by r4pt0s — APPROVED** [review]
🔥🔥🔥

**Pull request merged**
