### PR TITLE
Add a computer sprite to map_start in room 1 (issue #35)

### PR DESCRIPTION
**Pull request by Karine91**
The laptop sprite source is already mentioned in assets credits -> https://opengameart.org/content/lpc-revised-the-office
Added game object to the map and tested for interaction access

### CODE REVIEW

**Comment by Karine91** [comment]
Just merged the latest updates and cake bigger than laptop right on it)
image

**Comment by Karine91** [comment]
@r4pt0s should I make the laptop bigger and move left?

**Comment by r4pt0s** [comment]
@Karine91 do you want to fix it or should I create another issue for it?
I leave it up to you.

**Comment by Karine91** [comment]
Ok I will fix that

**Comment by r4pt0s** [comment]
@Karine91 you could try to change the stack order by using [k.z()](https://kaplayjs.com/doc/ctx/z/)

Or move the laptop a bit to the left. It has just to be reachable by the player fir interactions.

**Comment by Karine91** [comment]
@r4pt0s should cake be interactable?

**Comment by r4pt0s** [comment]
@Karine91 thar would be great, yes.

**Comment by Karine91** [comment]
@r4pt0s I'm not sure what those spawnpoints are, and why we need them for cake position

**Comment by Karine91** [comment]
@r4pt0s Ok I just moved computer like this
image

**Comment by r4pt0s** [comment]
@Karine91 that totally works. Would be so kind and merge the latest changes into your PR?
Then we are ready to merge 🚀

**Comment by Karine91** [comment]
done

**Comment by r4pt0s** [comment]
Thanks you @Karine91.
BTW, I love that you used query to get the position of the table. That's the reason why we set up everything we did + provided the additional map information.

**Pull request merged**
